---

- name: Nginx Log directory check if SELinux context information is present
  command: semanage fcontext --list -C
  failed_when: false
  register: _nginx_log_dir_fcontext
  when:
    # Redundant, but added to prevent E301 linting issue
    - ansible_facts.selinux.status == 'enabled'

- name: Nginx Log directory add SELinux context information
  command: semanage fcontext -a -e {{ nginx_log_dir }} {{ nginx_log_symlink_src }}
  when: >
    '{{ nginx_log_symlink_src }} = {{ nginx_log_dir }}' not in
    _nginx_log_dir_fcontext.stdout_lines
  register: _nginx_log_dir_fcontext_addition

- name: Nginx Log directory ensure SELinux context is correct in new dir
  command: "restorecon -R {{ nginx_log_symlink_src }}"
  when: _nginx_log_dir_fcontext_addition.changed

# Restore the SELinux context provided by the nginx package after the forced symlink
# creation in "Nginx Log directory symlink" breaks it.
- name: Nginx Log directory ensure SELinux context is correct in default location (symlink)
  command: "restorecon {{ nginx_log_dir }}"
  when: _nginx_log_dir_file_task.changed
