---

- name: Add EPEL repository (RedHat)
  yum:
    name: "epel-release"
    state: "present"
  when:
    - ansible_os_family == "RedHat"
    - not (ansible_distribution == 'Amazon' and ansible_distribution_version == '2')

- name: Add EPEL repository (Amazon Linux 2)
  shell: >
    set -o pipefail

    amazon-linux-extras list | grep -Eq 'epel\s+enabled' ||
    amazon-linux-extras install epel -y
  when:
    - ansible_distribution == 'Amazon'
    - ansible_distribution_version == '2'
